"""initial_schema

Revision ID: 220b3910ff68
Revises: 
Create Date: 2026-08-11 17:09:38.068826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220b3910ff68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index('ix_audit_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_business_id'), ['business_id'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index('ix_finding_audit_severity', ['audit_id', 'severity'], unique=False)

    op.create_table('pillar_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pillar_result', schema=None) as batch_op:
        batch_op.create_index('ix_pillar_audit', ['audit_id', 'pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_pillar_result_audit_id'), ['audit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pillar_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pillar_result_audit_id'))
        batch_op.drop_index('ix_pillar_audit')

    op.drop_table('pillar_result')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_audit_severity')
        batch_op.drop_index(batch_op.f('ix_finding_audit_id'))

    op.drop_table('finding')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_business_id'))
        batch_op.drop_index('ix_audit_business_created')

    op.drop_table('audit')
    op.drop_table('business')
    # ### end Alembic commands ###
